INDICE = 13
SOMA = 0
## INDICE E SOMA - VARIÁVEIS


for k in range(1, INDICE + 1):
  SOMA+= k
## FOR CRIA UM LAÇO QUE ITERA SOBRE OS VALORES E A CADA ITERAÇÃO O "K" ASSUME O VALOR DESSA SEQUENCIA

  print(SOMA)
  
## NO FINAL ELE MOSTRA A SOMA DE CADA ITERAÇÃO.
## NO FINAL O VALOR DA SOMA SERÁ 91

